language: php

php:
  - '7.2'

before_script:
  - php -v
  - composer install --prefer-dist --no-progress --no-suggest --no-interaction

script:
  - mkdir -p build/logs
#  - echo "Running PHP Unit test"
#  - php vendor/bin/phpunit --colors --coverage-text
#  - php vendor/bin/phpunit --colors
  - echo "Running PHP CodeSniffer"
  - php vendor/bin/phpcs --config-set ignore_warnings_on_exit 1
  - php vendor/bin/phpcs --standard=PSR12 -w --colors src
  - echo "Running PHP Mess Detector"
  - php vendor/bin/phpmd src text phpmd.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls
